name: angel3_jael
version: 8.3.0
description: Angel support for the Jael templating engine, similar to Blade or Liquid.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/jael/angel_jael
resolution: workspace
environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  angel3_framework: ^8.4.0
  jael3: ^8.0.0
  jael3_preprocessor: ^8.0.0
  belatuk_code_buffer: ^5.1.0
  belatuk_symbol_table: ^5.1.0
  file: ^7.0.0
  logging: ^1.2.0
dev_dependencies:
  angel3_test: ^8.2.0
  html: ^0.15.0
  test: ^1.24.0
  lints: ^6.0.0

