name: "angel3_auth_twitter"
description: Angel3 authentication strategy for Twitter login. Auto-signs requests.
version: 9.1.0
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/
issue_tracker: https://github.com/dart-backend/angel/issues

publish_to: none
resolution: workspace
environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  angel3_auth: ^9.0.0
  angel3_framework: ^9.0.0
  http: ^1.0.0
  path: ^1.9.0
  belatuk_oauth1: ^3.0.0
  dart_twitter_api: ^0.5.6+1
dev_dependencies:
  logging: ^1.2.0
  lints: ^6.0.0
