services:

  mongo:
    image: mongo:latest
    restart: no
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Qwerty
      MONGO_INITDB_DATABASE: local
    networks:
      - appnet

  mongo-express:
    image: mongo-express:latest
    restart: no
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Qwerty
      ME_CONFIG_MONGODB_URL: mongodb://root:Qwerty@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - appnet

networks:
  appnet:
