name: angel3_seo
version: 9.1.0
description: Helper infrastructure for building SEO-friendly Web backends in Angel3.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/
issue_tracker: https://github.com/dart-backend/angel/issues

resolution: workspace
environment:
  sdk: '>=3.13.0 <4.0.0'
dependencies:
  angel3_framework: ^9.0.0
  angel3_static: ^9.0.0
  file: ^7.0.0
  html: ^0.15.0
  http_parser: ^4.0.0
  path: ^1.9.0
dev_dependencies:
  angel3_test: ^9.0.0
  logging: ^1.2.0
  test: ^1.24.0
  lints: ^6.0.0
