// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:angel3_container_generator/angel3_container_generator.dart'
    as prefix0;
import 'package:reflectable/capability.dart' as prefix1;
import 'package:reflectable/mirrors.dart' as prefix2;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ContainedReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'ContainedReflectable',
            r'.ContainedReflectable',
            134217735,
            0,
            const prefix0.ContainedReflectable(),
            const <int>[0],
            const <int>[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix0.ContainedReflectable() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.contained],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(r'', 128, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.ContainedReflectable(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 1, 1, const <int>[],
            const <int>[0], const prefix0.ContainedReflectable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.ContainedReflectable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[1],
            const prefix0.ContainedReflectable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.ContainedReflectable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.ContainedReflectable(), const []),
        r.MethodMirrorImpl(
            r'capabilities',
            35651587,
            -1,
            -1,
            6,
            7,
            const <int>[5],
            const <int>[],
            const prefix0.ContainedReflectable(),
            const []),
        r.MethodMirrorImpl(
            r'canReflect',
            2097154,
            -1,
            -1,
            1,
            1,
            const <int>[],
            const <int>[2],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'reflect',
            2097154,
            -1,
            -1,
            8,
            8,
            const <int>[],
            const <int>[3],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'canReflectType',
            2097154,
            -1,
            -1,
            1,
            1,
            const <int>[],
            const <int>[4],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'reflectType',
            2097154,
            -1,
            -1,
            9,
            9,
            const <int>[],
            const <int>[5],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'findLibrary',
            2097154,
            -1,
            -1,
            10,
            10,
            const <int>[],
            const <int>[6],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'libraries',
            35651587,
            -1,
            -1,
            12,
            13,
            const <int>[11, 10],
            const <int>[],
            const prefix0.ContainedReflectable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'annotatedClasses',
            35651587,
            -1,
            -1,
            15,
            16,
            const <int>[14],
            const <int>[],
            const prefix0.ContainedReflectable(),
            const <Object>[override])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            1,
            const prefix0.ContainedReflectable(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            3,
            const prefix0.ContainedReflectable(),
            -1,
            18,
            18,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'reflectee',
            134348806,
            7,
            const prefix0.ContainedReflectable(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'reflectee',
            134348806,
            8,
            const prefix0.ContainedReflectable(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'type',
            134348806,
            9,
            const prefix0.ContainedReflectable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'type',
            134348806,
            10,
            const prefix0.ContainedReflectable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'libraryName',
            134348806,
            11,
            const prefix0.ContainedReflectable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix0.ContainedReflectable,
        bool,
        String,
        int,
        Type,
        prefix1.ReflectCapability,
        const m.TypeValue<List<prefix1.ReflectCapability>>().type,
        List,
        prefix2.InstanceMirror,
        prefix2.TypeMirror,
        prefix2.LibraryMirror,
        Uri,
        const m.TypeValue<Map<Uri, prefix2.LibraryMirror>>().type,
        Map,
        prefix2.ClassMirror,
        const m.TypeValue<Iterable<prefix2.ClassMirror>>().type,
        Iterable,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'capabilities': (dynamic instance) => instance.capabilities,
        r'canReflect': (dynamic instance) => instance.canReflect,
        r'reflect': (dynamic instance) => instance.reflect,
        r'canReflectType': (dynamic instance) => instance.canReflectType,
        r'reflectType': (dynamic instance) => instance.reflectType,
        r'findLibrary': (dynamic instance) => instance.findLibrary,
        r'libraries': (dynamic instance) => instance.libraries,
        r'annotatedClasses': (dynamic instance) => instance.annotatedClasses
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(r'reflectable://0/'),
            const prefix0.ContainedReflectable(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
